### PR TITLE
feat: astro-font - optimize fonts & prevent CLS

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
https://www.launchfa.st/features/astro-font

### CODE REVIEW

**Comment by aay7ush** [comment]
Thanks for improving the code

**Comment by rishi-raj-jain** [comment]
Hey @aay7ush, hearing those words make it all worth it. Thank you so much for making my day!

**Comment by aay7ush** [comment]
> Hey @aay7ush, hearing those words make it all worth it. Thank you so much for making my day!

You're welcome! I'm glad I could make your day better. Also, can we connect on LinkedIn? I tried sending you a connection request but it's asking for your email.

**Comment by rishi-raj-jain** [comment]
rishi18304@iiitd.ac.in

**Pull request merged**
